### ISSUE TITLE
Pop-ed out components

### ISSUE THREAD

**Issue by jdriesen** [quasarcast/takeoff#2]
When a component is "pop-ed out" and the user clicks the "close button", the component seems to be "lost"... (completely "gone").
Would be nice to have this "pop-ed in" again...

**Comment by ldiebold** [comment]
yea this seems to be broken. Thanks @jdriesen!

**Comment by ldiebold** [comment]
Fixed... I believe chrome made the `onunloadpage` stricter, so I had to do a pretty funky workaround by checking `onpagehide` event instead.
